# Generated by Django 5.2.7 on 2025-10-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('shopcart_item_connection', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['user_id'], name='orders_user_id_4e08b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('product_variation', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rest_api.order')),
            ],
            options={
                'db_table': 'order_items',
                'indexes': [models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'), models.Index(fields=['status'], name='order_items_status_c06719_idx')],
            },
        ),
    ]
