# Generated by Django 5.2.7 on 2025-10-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopcart_item_connection',
        ),
    ]
