# Generated by Django 5.2.7 on 2025-10-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_order_shopcart_item_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Cancelled')], default=1),
        ),
    ]
