# Generated by Django 5.2.7 on 2025-10-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopcart_item_connection',
        ),
    ]
